"""
Reporter layer: AnalysisResult[] → Markdown report

Single responsibility: format AnalysisResult data into a readable report.
No parsing logic. No AI logic. No business decisions.
"""

import sys
from datetime import datetime, timezone
from pathlib import Path

from analyzer.models import AnalysisResult

_REPORTS_DIR = Path(__file__).parent.parent / "reports"

_SEVERITY_ICON = {
    "critical": "🔴",
    "high": "🟠",
    "medium": "🟡",
    "low": "🟢",
}


def _format_duration(ms: int) -> str:
    return f"{ms / 1000:.1f}s" if ms >= 1000 else f"{ms}ms"


def _format_timestamp(ts: str) -> str:
    try:
        return datetime.fromisoformat(ts.replace("Z", "+00:00")).strftime(
            "%Y-%m-%d %H:%M UTC"
        )
    except ValueError:
        return ts


def _trim_error(message: str) -> str:
    """Drop the Playwright 'Call log:' section — it's internal trace, not signal."""
    return message.split("Call log:")[0].strip()


def _executive_summary(results: list[AnalysisResult]) -> str:
    counts = {s: 0 for s in ("critical", "high", "medium", "low")}
    for r in results:
        if r.severity in counts:
            counts[r.severity] += 1

    return "\n".join([
        "## Executive Summary",
        "",
        f"**Total failures analyzed:** {len(results)}",
        "",
        "| Severity        | Count |",
        "|---|---|",
        f"| 🔴 Critical     | {counts['critical']} |",
        f"| 🟠 High         | {counts['high']} |",
        f"| 🟡 Medium       | {counts['medium']} |",
        f"| 🟢 Low          | {counts['low']} |",
    ])


def _failure_section(result: AnalysisResult, index: int) -> str:
    f = result.failure
    confidence = f"{int(result.confidence * 100)}%"
    error_snippet = _trim_error(f.error_message)

    action_items = "\n".join(f"- [ ] {step}" for step in result.suggested_steps)

    return "\n".join([
        f"## {index}. {f.test_title}",
        "",
        "### Test Details",
        "",
        "| Field | Value |",
        "|---|---|",
        f"| File | `{f.file}` |",
        f"| Browser | {f.browser} |",
        f"| Duration | {_format_duration(f.duration_ms)} |",
        f"| Error type | `{f.error_type}` |",
        f"| Timestamp | {_format_timestamp(f.timestamp)} |",
        "",
        "### AI Triage",
        "",
        "| Field           | Value |",
        "|---|---|",
        f"| Probable cause  | {result.probable_cause} |",
        f"| Severity        | {_SEVERITY_ICON.get(result.severity, '')} {result.severity.upper()} |",
        f"| Confidence      | {confidence} |",
        f"| Business impact | {result.business_impact} |",
        "",
        "### Recommended Actions",
        "",
        action_items,
        "",
        "### Raw Error Snapshot",
        "",
        "```",
        error_snippet,
        "```",
    ])


def generate(results: list[AnalysisResult]) -> str:
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    browsers = ", ".join(sorted({r.failure.browser for r in results}))

    header = "\n".join([
        "# AI Regression Analysis Report",
        "",
        f"Generated: {now}  |  Failures: {len(results)}  |  Browsers: {browsers}",
        "",
        "---",
    ])

    sections = [
        header,
        _executive_summary(results),
        "---",
        *[_failure_section(r, i + 1) for i, r in enumerate(results)],
        "---",
        "_Generated by AI Regression Analyzer_",
    ]

    return "\n\n".join(sections)


def write(report: str, path: Path = _REPORTS_DIR / "failure-report.md") -> Path:
    path.parent.mkdir(exist_ok=True)
    path.write_text(report)
    return path


def main() -> None:
    from analyzer.parser import parse
    from analyzer.triage import analyze

    results_path = sys.argv[1] if len(sys.argv) > 1 else "test-results/results.json"

    failures = parse(results_path)
    if not failures:
        print("No failures found.")
        return

    results = [analyze(f) for f in failures]
    report = generate(results)
    output = write(report)
    print(f"Report written: {output}")


if __name__ == "__main__":
    main()
